spring:
  application:
    name: gateway
  redis:
    host: 127.0.0.1
    port: 6379
    password: 311324
  cloud:
    gateway:
      routes:
       - id: system
         uri: lb://system
         predicates:
           # Path要大写
           - Path=/system/**
        # https://cloud.spring.io/spring-cloud-gateway/reference/html/
         filters:
           - LoginAdmin

       - id: business
         uri: lb://business
         predicates:
           - Path=/business/**
         filters:
           - LoginAdmin

       - id: file
         uri: lb://file
         predicates:
           - Path=/file/**
         filters:
           - LoginAdmin

server:
  port: 18000

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka/
